version: '3.7'
services:
    web:
        image: nginx
        volumes:
            - .:/usr/share/nginx/html
        ports:
            - 8080:80
    data_to_json:
        build:
            context: .
            target: jq
        working_dir: /app
        volumes:
            - .:/app
        command: 'bash data_to_json.sh'
